### ISSUE TITLE
[README]: we need a good readme 

### ISSUE THREAD

**Issue by Kellsonphilips** [AliReza1083/Asakatsu#1]
So others participating in the Asakatsu can get to know about the repo and maybe contribute.
This might be another open source.

**Comment by alisamadiii** [comment]
Yes @Kellsonphilips

**Comment by alisamadiii** [comment]
But I'll give the source codes to Miss Avie because this is her Project.

**Comment by alisamadiii** [comment]
Can You add your own goal in the json file?

**Comment by Kellsonphilips** [comment]
I will do that later in the when am creating a new goal because I'm completing my first issue today.

**Comment by alisamadiii** [comment]
NO Philips,
it is just for checking, just test it.

**Comment by Kellsonphilips** [comment]
Alright let me add some goals in the JSON and make a PR

**Comment by alisamadiii** [comment]
Thanks for that Philips

**Comment by alisamadiii** [comment]
I've made a PR with my second Account, but I am not going to merge it, it was just for checking.
when you made a PR, You can see the website live.

check this website:
https://github.com/AliReza1083/Asakatsu/pull/6

**Comment by alisamadiii** [comment]
Can you make the README file?

**Comment by Kellsonphilips** [comment]
Ok,  I will try to do that.

**Comment by alisamadiii** [comment]
I don't think there is need to make it...
because Miss Avie should make another repo for this.
what you think?

**Comment by alisamadiii** [comment]
I'll give the website to Miss Avie...

**Comment by alisamadiii** [comment]
You can talk with her about this...

**Comment by Kellsonphilips** [comment]
I will make the readme and if she wants to make another repo. She can take all source code and readme together. It has no problem.

**Comment by alisamadiii** [comment]
GOT IT 💪💪🚀✌️

**Comment by AliReza1083** [comment]
Can I ask something @Kellsonphilips ?

**Comment by alisamadiii** [comment]
Now the Profile.json is updated in the Repo, but not updated in my VSCODE to continue working...
how to get all the things that has been updated?
did you get what I mean?

**Comment by Kellsonphilips** [comment]
Yes ask me

**Comment by Kellsonphilips** [comment]
Ok, you didn't send the code from your PC to GitHub. 
You git clone the repo to your computer and now work on the cloned repo directly.

If you work on anything then you can push it with "git push origin <branch-name>" press enter and I will be sent to the repo on GitHub

**Comment by Kellsonphilips** [comment]
But if you pushed to GitHub using the repo URL then you can always use "git pull origin main" to fetch all the updates on GitHub into your local directory.

**Comment by alisamadiii** [comment]
Oh thanks for that Philips

**Comment by Kellsonphilips** [comment]
Did you push the source code from your local directory to GitHub using the repo URL or you simply uploaded the files to GitHub?

**Comment by alisamadiii** [comment]
repo URL,
But I got it. Thanks

**Comment by Kellsonphilips** [comment]
I'm doing that now

**Comment by alisamadiii** [comment]
@Kellsonphilips 
These 3 links don't work properly.
![image](https://user-images.githubusercontent.com/99729607/197165899-826901b6-ffde-4dbc-b469-fa26550e4d4a.png)

**Comment by Kellsonphilips** [comment]
I will fix that later when i add contributor file and the rest

**Comment by alisamadiii** [comment]
Got it @Kellsonphilips
