### ISSUE TITLE
Vercel / Netlify

### ISSUE THREAD

**Issue by alisamadiii** [AliReza1083/Asakatsu#12]
We need to connect this Repo to vercel or netlify...
@avie-dev @Kellsonphilips

**Comment by Kellsonphilips** [comment]
If Avie wants then we will deploy it either by you or me. but I feel @avie-dev should deploy it to her personal Vercel or Netlify account.

**Comment by alisamadiii** [comment]
One more question:
Are you going to import it manually or import an existing project?
@Kellsonphilips

**Comment by Kellsonphilips** [comment]
@avie-dev please deploy this site to Netlify or Vercel. 
We want it hosted in your account rather

**Comment by alisamadiii** [comment]
@avie-dev 
Are you going to import it manually or import an existing project?

**Comment by alisamadiii** [comment]
@Kellsonphilips 
I think we should talk with them in Twitter group.
They don't seem to be active in GitHub

**Comment by Kellsonphilips** [comment]
Yes , she is not responding here

**Comment by avie-dev** [comment]
Sorry about that was not feeling well plus busy. I can check this to today.

**Comment by tobySolutions** [comment]
You should try to rename the site on netlify.

**Comment by alisamadiii** [comment]
@tobySolutions  We are waiting to connect the website to Netlify.
@avie-dev

**Comment by avie-dev** [comment]
@AliReza1083 @Kellsonphilips @tobySodone here. Can you check if it's okay?
https://asakatsu.netlify.app/

**Comment by alisamadiii** [comment]
@avie-dev 
did you buy it?

**Comment by alisamadiii** [comment]
The website is working fine.

**Comment by alisamadiii** [comment]
Done

**Comment by Kellsonphilips** [comment]
Wonderful 👏🏼
