### ISSUE TITLE
[BUG]: Theme changer being the opposite

### ISSUE THREAD

**Issue by AryanBabber** [AliReza1083/Asakatsu#20]
This issue is regarding the theme where the default is dark and when I try to turn on the dark mode shown below, it switches to light mode.

![image](https://user-images.githubusercontent.com/86878236/210542166-0e914eb2-95af-49ae-ba5b-ddff70430d91.png)

**Comment by AryanBabber** [comment]
Can I work on this? @AliReza1083 @Kellsonphilips

**Comment by alisamadiii** [comment]
Thanks for telling us this issue.
Would you please tell us, How are you going to fix it?

**Comment by AryanBabber** [comment]
Try this? @AliReza1083 
![image](https://user-images.githubusercontent.com/86878236/210845811-55e183ca-2702-4149-8d3c-f82bb164ab50.png)

**Comment by AryanBabber** [comment]
But then, I am unable to run it locally because of an error in Firebase so you might try it on your device

**Comment by alisamadiii** [comment]
Can we change the Dark Mode text to Light Mode for making our work easy?

**Comment by AryanBabber** [comment]
Yep, that'd be better

**Comment by AliReza1083** [comment]
Are you willing to do it?

**Comment by alisamadiii** [comment]
Fixed,
Thanks for the issue Aryan,
Hope to see more issues to improve the website
