### ISSUE TITLE
Firebase error

### ISSUE THREAD

**Issue by AryanBabber** [AliReza1083/Asakatsu#21]
I am seeing this error when I try to run it locally to fix bugs. Is this normal?

![image](https://user-images.githubusercontent.com/86878236/210845685-d816159c-2a96-4cef-b0ac-d4d5fef7b595.png)

**Comment by alisamadiii** [comment]
I see Aryan,
Have you ever worked with Firebase before?
There must be a file which will connect your application to firebase DB, and We are not allowed to push it to GitHub.
It must be private.

**Comment by AryanBabber** [comment]
@AliReza1083 I haven't, unfortunately. I just wanted to make the changes and fix the issue I raised before this issue...

**Comment by alisamadiii** [comment]
Ok Aryan,
It is not a problem, You'll learn it in the near future.
