### ISSUE TITLE
Lots of Space is left Empty in the Home Page

### ISSUE THREAD

**Issue by bharathkalyans** [AliReza1083/Asakatsu#24]
* Increasing the height of the div will give a better look to the home page!

![shapes](https://user-images.githubusercontent.com/49526472/232004914-a1b7541e-b37f-4e3f-8887-17f71d01e520.png)

**Comment by alisamadiii** [comment]
Nice one,
Are you going to do it?

**Comment by bharathkalyans** [comment]
> Nice one, Are you going to do it?

Sure!

**Comment by alisamadiii** [comment]
This issue will be assigned to you.
Good Luck

We are using Firebase for the DB.

**Comment by bharathkalyans** [comment]
yeah, I am getting FireBaseConfig error! Will look into it. I have never used firebase so, it might take time!😅

**Comment by bharathkalyans** [comment]
@AliReza1083 Have you gone through the PR?
