### ISSUE TITLE
Home button

### ISSUE THREAD

**Issue by Kellsonphilips** [AliReza1083/Asakatsu#5]
Add a home button that redirects back to the landing page when clicked

**Comment by alisamadiii** [comment]
I'll add that once the logo is ready.
thanks for that Philips

**Comment by Kellsonphilips** [comment]
Oh okay, you want to use the logo as the home button. Good idea

**Comment by alisamadiii** [comment]
Yeah

**Comment by alisamadiii** [comment]
DONE
