### ISSUE TITLE
Making the home button visible on all pages

### ISSUE THREAD

**Issue by Kellsonphilips** [AliReza1083/Asakatsu#9]

**Comment by alisamadiii** [comment]
I'll add that, Still thinking where to put it...hhh

**Comment by Kellsonphilips** [comment]
Haha let me see how that looks lol

**Comment by Kellsonphilips** [comment]
I think we will need a sticky nav bar at the top

**Comment by alisamadiii** [comment]
Can you make a README file for this repo?

**Comment by alisamadiii** [comment]
So that Everyone knows how to join and add their goals...

**Comment by Kellsonphilips** [comment]
I was busy but I will make the readme. Let me gather the links and processes needed and put it in the Readme

**Comment by alisamadiii** [comment]
OK

**Comment by alisamadiii** [comment]
DONE
